[package]
name = "regex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.6"
bitflags = "1.3.2"
itertools = "0.10.3"
enum-display-derive = "0.1.1"